# Generated by Django 3.1.3 on 2023-05-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='last_udpated_on',
            new_name='last_updated_on',
        ),
    ]
